[workspace]
authors = ["Tadej Svetina <tadej.svetina@gmail.com>"]
channels = ["conda-forge"]
name = "cpp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ninja = ">=1.13.2,<2"
cmake = ">=4.2.0,<5"
clangxx = ">=21.1.6,<22"
libcxx = ">=21.1.6,<22"
libcxx-devel = ">=21.1.6,<22"
libunwind = ">=1.8.3,<2"
clang-tools = ">=21.1.6,<22"
include-what-you-use = ">=0.25,<0.26"
lld = ">=21.1.6,<22"
llvm-tools = ">=21.1.6,<22"
hyperfine = ">=1.20.0,<2"
